name: 'Cleanup'

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: 'working-directory'
        type: choice
        options:
          - envs/prod/
          - envs/dev/

env:
  TF_LOG: INFO
  FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BACKEND_ROLE_ARN: ${{ secrets.BACKEND_ROLE_ARN }}
  BACKEND_BUCKET: ${{ secrets.BACKEND_BUCKET }}
  BACKEND_DYNAMO_DB: ${{ secrets.BACKEND_DYNAMODB_TABLE }}

jobs:
  terraform:
    name: 'Cleanup'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.event.inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      - name: terraform init
        id: init
        run: |
          terraform init -input=false \
          -backend-config="role_arn=$BACKEND_ROLE_ARN" \
          -backend-config="bucket=$BACKEND_BUCKET" \
          -backend-config="dynamodb_table=$BACKEND_DYNAMODB_TABLE"

      - name: terraform destroy
        id: destroy
        run: terraform destroy -no-color -input=false -lock-timeout=60m -auto-approve
